dependencies:
 - numpy=1.19.2
 - pip=21.0.1
 - python=3.9
 - pip:
   - matplotlib==3.4.3
   - git+https://github.com/emolter/pylanetary@active-dev
   - git+https://github.com/astropy/astroquery@main
   - scipy==1.9.3
   - pandas==1.3.4
   - scikit-image==0.18.3
   - git+https://github.com/keflavich/image_registration@master
   - shift-stack-moons==0.0.6
   - pytest==6.2.4
   - photutils==1.4.0